language: ruby
dist: focal
cache: bundler
rvm:
  - 2.7.1

services:
  - postgresql

jobs:
  include:
    - name: Test
      addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      before_script:
        - pg_config --version
        - psql -c 'create database "test-database";'
      before_install:
        - gem install bundler
      env:
        - SNS_RETRIES=0
        - SNS_TIMEOUT=1
      script: bundle exec rspec

    - name: Rubocop
      script: bundle exec rubocop -D -c .rubocop.yml

